### ISSUE TITLE
svelte-kit dev is no longer available — use vite dev instead

### ISSUE THREAD

**Issue by alexander-mart** [Uthpala/starter-kit#2]
```
$ pnpm run dev -- --open
> svelte-kit dev is no longer available — use vite dev instead
  1. Install vite as a devDependency with npm/pnpm/etc
  2. Create a vite.config.js with the @sveltejs/kit/vite plugin (see below)
  3. Update your package.json scripts to reference `vite dev` instead of `svelte-kit dev`
  ```
  
Detailed:
Svelte-Kit Dev Is No Longer Available Use Vite Dev Instead
https://www.youtube.com/watch?v=DSaRNhPpwMM
  
After that:

```
failed to load config from /home/user/projects/starter-kit/vite.config.js
error when starting dev server:
file:///home/user/projects/starter-kit/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.1.0_svelte@3.52.0+vite@2.9.15/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:389
import { createFilter } from "vite";
         ^^^^^^^^^^^^
SyntaxError: Named export 'createFilter' not found. The requested module 'vite' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vite';
const { createFilter } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/home/user/projects/starter-kit/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:61925:31)
    at async resolveConfig (/home/user/projects/starter-kit/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:61456:28)
    at async createServer (/home/user/projects/starter-kit/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/chunks/dep-689425f3.js:60111:20)
    at async CAC.<anonymous> (/home/user/projects/starter-kit/node_modules/.pnpm/vite@2.9.15/node_modules/vite/dist/node/cli.js:688:24)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by alexander-mart** [comment]
https://www.youtube.com/watch?v=DSaRNhPpwMM
